hash-format = "sha256"

[[files]]
file = "config/defaultoptions/servers.dat"

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
metafile = true

[[files]]
file = "mods/architects-palette-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/autorun.pw.toml"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chattoggle.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
metafile = true

[[files]]
file = "mods/cleancut.pw.toml"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/convenient-decor.pw.toml"
metafile = true

[[files]]
file = "mods/convenient-name-tags.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-garnished.pw.toml"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
metafile = true

[[files]]
file = "mods/displaycase.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/dustrial-decor.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emicompat.pw.toml"
metafile = true

[[files]]
file = "mods/emienchants.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastback.pw.toml"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
metafile = true

[[files]]
file = "mods/foodeffecttooltips.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fullstack-watchdog.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
metafile = true

[[files]]
file = "mods/hex-circus.pw.toml"
metafile = true

[[files]]
file = "mods/hex-research.pw.toml"
metafile = true

[[files]]
file = "mods/hex-ways.pw.toml"
metafile = true

[[files]]
file = "mods/hexal.pw.toml"
metafile = true

[[files]]
file = "mods/hexbound-fork.pw.toml"
metafile = true

[[files]]
file = "mods/hexdebug.pw.toml"
metafile = true

[[files]]
file = "mods/hexgloop.pw.toml"
metafile = true

[[files]]
file = "mods/hexical.pw.toml"
metafile = true

[[files]]
file = "mods/hexkeys.pw.toml"
metafile = true

[[files]]
file = "mods/hexkinetics.pw.toml"
metafile = true

[[files]]
file = "mods/hexlink.pw.toml"
metafile = true

[[files]]
file = "mods/hextended-staves.pw.toml"
metafile = true

[[files]]
file = "mods/hextweaks.pw.toml"
metafile = true

[[files]]
file = "mods/hexvr.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/ingredient-extension-api.pw.toml"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/kettle.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/labels.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
metafile = true

[[files]]
file = "mods/led.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/magic-origins.pw.toml"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
metafile = true

[[files]]
file = "mods/mcr_blahaj.pw.toml"
metafile = true

[[files]]
file = "mods/mediaworks.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/mirage_mod.pw.toml"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/packages.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/redstonepen.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/retraining.pw.toml"
metafile = true

[[files]]
file = "mods/revelationary.pw.toml"
metafile = true

[[files]]
file = "mods/runelic.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/simple-cobblestone-generator.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spectrum.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
metafile = true

[[files]]
file = "mods/tinkerers-smithing.pw.toml"
metafile = true

[[files]]
file = "mods/tis3d.pw.toml"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/watson.pw.toml"
metafile = true

[[files]]
file = "mods/wnboi.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/xl-c2s-packets-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true
