name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f70cbedda8766affa5acf574f3ea80a83bed7c2ae06db254e2fa0c9f15400ed"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
no-internal-hashes = false
