name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cce571e41132bcb2d441ec1e9f09c1b8af798c9e8469d8412b56d7fb7938960"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
