name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b05ed3d1ef2edb3bb536398a67fd2e871202dc5f1b3c17318ad2e0e0a5b39158"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
no-internal-hashes = false
