name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d1fdeef65246e4a3e0ed82df9b5f03fb2f531908c967e89d918bebc4a6388e9"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
