name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "993d9c6d5f33c952b0482156e4240bc54a9270f58ba6a8268a44722844c5d039"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
no-internal-hashes = false
