name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fe2e417deae3bbd35553e6c64b3b8aff0f2559840dd8a559a7aeb3e59fe251e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
no-internal-hashes = false
