name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "526391d8473e9c6c3fcfe1997d8b064daf89cdafb25c8f2b709f5c3d3b653bf3"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
