name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28eca93de7f623dc6caeec70507fb028c888a82485f30b285985b8412e6a55a9"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
no-internal-hashes = false
