name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "782990690cb0677f33d8c15198824897999bced1325f91e01934b82f528f16bc"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
