name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a15b09f253dec81e30f0e731b6121ee02b23c199c13ca85bfb30841296844edd"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
