name = "Hexxytest++"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e40d5278f8f909ce4e06b5a728f078fe633af9e29e0c55cf1ab30e7b493b222"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
