
#.
#Settings for the estrogen patches
[estrogenPatches]
	#.
	#§4THIS ONLY WORKS ON §fFABRIC§7/§dQUILT§4 MOD LOADER
	#The stack size limit of estrogen patches
	#[@cui:RequiresReload:both]
	#Range: 1 ~ 64
	estrogenPatchesStackSize = 4

#.
#Settings which are more fun and not fit for survival
[minigame]
	#.
	#Enable/Disable all minigame settings
	minigameEnabled = false
	#.
	#Gives you permanent, unremovable Girl Power Effect
	permaDash = true
	#.
	#The level of Girl Power Effect when Perma-Dash is enabled
	#Range: 0 ~ 255
	permaDashAmount = 0

