
[network]
	#The maximum number of particle effects data transfer may trigger per tick.
	#When this is exceeded, throttling kicks in.
	#Range: 1 ~ 500
	maxParticlesPerTick = 5
	#The maximum number of status packets modules may send per tick.
	#When this is exceeded, throttling kicks in.
	#Range: 1 ~ 500
	maxPacketsPerTick = 10

[controller]
	#The maximum number of casings a single controller supports.
	#Range: 1 ~ 64
	maxCasingsPerController = 16

[module]

	[module.execution]
		#The maximum number of lines an ASM program for an execution node may have. Use zero to remove the limit.
		#Range: 0 ~ 200
		maxLinesPerProgram = 40

	[module.infrared]
		#The maximum number of infrared packets that can be stored in the receiver's buffer.
		#Range: 1 ~ 64
		maxInfraredQueueLength = 16

